# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{newrelic_api}
  s.version = "1.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["New Relic"]
  s.date = %q{2011-01-12}
  s.description = %q{Use this gem to access New Relic application information via a REST api}
  s.email = %q{support@newrelic.com}
  s.extra_rdoc_files = [
    "CHANGELOG",
    "README.rdoc"
  ]
  s.files = [
    ".project",
    "CHANGELOG",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/active_resource_associations.rb",
    "lib/new_relic_api.rb",
    "newrelic_api.gemspec",
    "test/integration/newrelic_api_test.rb",
    "test/test_helper.rb"
  ]
  s.homepage = %q{http://www.github.com/newrelic/newrelic_api}
  s.licenses = ["MIT"]
  s.rdoc_options = ["--line-numbers", "--title", "Documentation and helper code for the New Relic API", "-m", "README.rdoc"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Documentation and helper code for the New Relic API}
  s.test_files = [
    "test/integration/newrelic_api_test.rb",
    "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rails>, ["= 3.0.3"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<shoulda>, ["~> 2.10.3"])
      s.add_development_dependency(%q<ci_reporter>, ["= 1.6.0"])
      s.add_development_dependency(%q<rdiscount>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, [">= 3.3"])
    else
      s.add_dependency(%q<rails>, ["= 3.0.3"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<shoulda>, ["~> 2.10.3"])
      s.add_dependency(%q<ci_reporter>, ["= 1.6.0"])
      s.add_dependency(%q<rdiscount>, [">= 0"])
      s.add_dependency(%q<rdoc>, [">= 3.3"])
    end
  else
    s.add_dependency(%q<rails>, ["= 3.0.3"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<shoulda>, ["~> 2.10.3"])
    s.add_dependency(%q<ci_reporter>, ["= 1.6.0"])
    s.add_dependency(%q<rdiscount>, [">= 0"])
    s.add_dependency(%q<rdoc>, [">= 3.3"])
  end
end

